config/routes.rb
Rails.application.routes.draw do
  get 'admin/login'
  get 'admin/logout'
  post 'admin/login'
  

  resources :emps

  resources :companies

  resources :books

	get "home/index"

end

app/models/book.rb
class Book < ActiveRecord::Base
	
	 self.per_page = 5
validates :name, presence: true
validates :name, uniqueness: true
validates :author, presence: true
validates :name, length: { minimum: 3,message: "Please enter atleast 3 chars" }

before_save :merge_book_name

after_save :confirm_message

def merge_book_name
	self.name = self.name + " by "+ self.author
end

def confirm_message
	puts "Email has been sent to admin"
end


end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :emps
end

app/models/emp.rb
class Emp < ActiveRecord::Base
  belongs_to :company
end

app/models/employee.rb
class Employee < ActiveRecord::Base
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def login
	  if request.post?
	     if params[:admin][:name] == "admin" and params[:admin][:password]=="password"
		     session[:admin]="admin loggedin"
		     redirect_to :controller=>:books
	    else
		    flash[:notice] = "Invalid uesername/password"
		    render :action=>:login
	    end
	  end
  end
  
  def logout
	  session[:admin]=nil
	  flash[:notice] = "You are logged out"
	  redirect_to :action=>:login
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  
  before_filter :check_admin_loggedin

  # GET /books
  # GET /books.json
  def index
	  a = 10
	  
    @books = Book.paginate(:page => params[:page])
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
	Notification.send_email_to_admin(@book).deliver
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :author)
    end
    
    def check_admin_loggedin
	    
	    if session[:admin].nil?
		    flash[:notice] = "Please login as a Admin to visit the books page"
		    redirect_to :controller=>:admin,:action=>:login
	    end
	    
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :year)
    end
end

app/controllers/emps_controller.rb
class EmpsController < ApplicationController
  before_action :set_emp, only: [:show, :edit, :update, :destroy]

  # GET /emps
  # GET /emps.json
  def index
    @emps = Emp.all
  end

  # GET /emps/1
  # GET /emps/1.json
  def show
  end

  # GET /emps/new
  def new
    @emp = Emp.new
  end

  # GET /emps/1/edit
  def edit
  end

  # POST /emps
  # POST /emps.json
  def create
    @emp = Emp.new(emp_params)

    respond_to do |format|
      if @emp.save
        format.html { redirect_to @emp, notice: 'Emp was successfully created.' }
        format.json { render :show, status: :created, location: @emp }
      else
        format.html { render :new }
        format.json { render json: @emp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emps/1
  # PATCH/PUT /emps/1.json
  def update
    respond_to do |format|
      if @emp.update(emp_params)
        format.html { redirect_to @emp, notice: 'Emp was successfully updated.' }
        format.json { render :show, status: :ok, location: @emp }
      else
        format.html { render :edit }
        format.json { render json: @emp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emps/1
  # DELETE /emps/1.json
  def destroy
    @emp.destroy
    respond_to do |format|
      format.html { redirect_to emps_url, notice: 'Emp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emp
      @emp = Emp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def emp_params
      params.require(:emp).permit(:name, :age, :email, :company_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/emps_helper.rb
module EmpsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/login.html.erb
<h2>Admin Login</h2>

<%=  flash[:notice] %>

<%= form_for(:admin) do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit "Login" %>
  </div>
<% end %>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.author %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>




<div class="apple_pagination">
<%= will_paginate @books %>
</div>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.year %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @company.year %>
</p>

Employees:<br />
<% @company.emps.each do |e| %>

Name : <%= e.name %><br />
Age : <%= e.age %><br />
Email: <%= e.email %><br />

<% end %>
<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/emps/_form.html.erb
<%= form_for(@emp) do |f| %>
  <% if @emp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@emp.errors.count, "error") %> prohibited this emp from being saved:</h2>

      <ul>
      <% @emp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br>
    <%= f.text_field :company_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/emps/edit.html.erb
<h1>Editing emp</h1>

<%= render 'form' %>

<%= link_to 'Show', @emp %> |
<%= link_to 'Back', emps_path %>

app/views/emps/index.html.erb
<h1>Listing emps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Email</th>
      <th>Company</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @emps.each do |emp| %>
      <tr>
        <td><%= emp.name %></td>
        <td><%= emp.age %></td>
        <td><%= emp.email %></td>
        <td><%= emp.company.name %></td>
        <td><%= link_to 'Show', emp %></td>
        <td><%= link_to 'Edit', edit_emp_path(emp) %></td>
        <td><%= link_to 'Destroy', emp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Emp', new_emp_path %>

app/views/emps/new.html.erb
<h1>New emp</h1>

<%= render 'form' %>

<%= link_to 'Back', emps_path %>

app/views/emps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @emp.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @emp.age %>
</p>

<p>
  <strong>Email:</strong>
  <%= @emp.email %>
</p>

<p>
  <strong>Company:</strong>
  <%= @emp.company.name %>
</p>

<%= link_to 'Edit', edit_emp_path(@emp) %> |
<%= link_to 'Back', emps_path %>

app/views/home/index.html.erb
<h1>Welcome to my first Rails page</h1>

<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:search_tag, "Search for:") %><br />
  <%= text_field_tag(:search_tag) %><br />
  
  
  <%= check_box_tag(:pet_dog) %>
<%= label_tag(:pet_dog, "I own a dog") %><br />
  <%= submit_tag("Search") %>
  
  <%= radio_button_tag(:age, "child") %>
<%= label_tag(:age_child, "I am younger than 21") %><br />

<%= month_field(:user, :birthday_month) %><br />
<%= week_field(:user, :birthday_week) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MayBatch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="main">
    <div id="header">  
      <h1>My <span>First Rails App</span></h1>	
	  <h2>Sample Project</h2>
    </div><!--close header-->			
    <div class="container_header"><p>&nbsp;</p></div>
    <div id="site_background"> 
      <div id="banner">  
		<div id="banner_content">
		</div><!--close banner_content-->	
      </div><!--close banner-->		
	  <div id="site_content">
	    <div id="menubar">
          <ul class="lavaLampWithImage" id="lava_menu">
            <li class="current"><a href="index.html">Home</a></li>
            <li><a href="ourwork.html">Our Work</a></li>
            
            <li><a href="projects.html">Projects</a></li>
<% if session[:admin] %>				
<li><a href="/admin/logout">Logged in as Admin.  Admin Logout</a></li>
<% else %>
<li><a href="/admin/login"> Admin Login</a></li>
<% end %>          </ul>
	      <div id="contact">
	        <a href="#"><img src="/assets/icons/twitter.png" alt="twitter" /></a>
            <a href="#"><img src="/assets/icons/facebook.png" alt="facebook" /></a>
            <a href="#"><img src="/assets/icons/linkedin.png" alt="linkedin" /></a>
	      </div><!--close contact-->
	    </div><!--close menubar-->	
        <div id="content">
          <div class="content_item">
            <%= yield %>
            		  </div><!--close content_item-->	
	      
		  <div class="sidebar_container">       
		    <div class="sidebar">
              <div class="sidebar_item">
                <h2>Latest Blog</h2>
			    <h4>April 2012</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque cursus tempor enim.</p>
		          <a href="#">Read more</a>
              </div><!--close sidebar_item--> 
            </div><!--close sidebar-->     		
		    <div class="sidebar">
              <div class="sidebar_item">
                <h2>Latest Blog</h2>
		  	    <h4>April 2012</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque cursus tempor enim.</p>
		          <a href="#">Read more</a>
              </div><!--close sidebar_item--> 
            </div><!--close sidebar-->  
		    <div class="sidebar">
              <div class="sidebar_item">
                <h2>Latest Blog</h2>
			    <h4>April 2012</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque cursus tempor enim.</p>
		          <a href="#">Read more</a>
              </div><!--close sidebar_item--> 
            </div><!--close sidebar-->  
           </div><!--close sidebar_container-->	
           <br style="clear:both;" />
        </div><!--close content-->	
      </div><!--close site_content-->	
	</div><!--close site_background-->	
    <div id="footer">  
	  <div id="footer_content">
	  &copy; All rights reserved - MyApp
      </div><!--close footer_content-->	
    </div><!--close footer-->	
  </div><!--close main-->	


</body>
</html>

app/views/notification/send_email_to_admin.html.erb
Hi Admin<br />
<br />

A new book has been added to our DB!

<br />

Here are the details<br/><br />

Name : <%= @book_name %><br />
Author : <%= @book_author %><br />
<br >
<br />


Thanks
Notification Team